name: Vercel Flask App

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-18.04

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_DB: vercel_test
          POSTGRES_PASSWORD: vercel123
          POSTGRES_USER: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v2

      - name: Setup Python 3
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements-dev.txt

      - name: Test with pytest
        run: pytest --cache-clear
        env:
          FLASK_APP: app
          DATABASE_URI: postgresql://postgres:vercel123@localhost/vercel_test
